config/routes.rb
Shoplist::Application.routes.draw do
  
  devise_for :users
  root 'lists#index'
  
  resources :products
  resources :places
  resources :items
  resources :lists
  
  post 'lists/:id' => 'lists#show', as: :go_back_to_list

  

end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :items
  belongs_to :user
  
  validates :list_name, presence: true
    
end

## getting current list ID
def curr_list_id
  l = List.find(params[:id])[:id]
  return l
end

## getting current user email
def curr_user_email
  e = User.find(current_user)[:email]
  return e
end

## getting list's creator ID
def created_by_id(id)
  listcreatorid = List.find(id)[:user_id]
  return listcreatorid
end

## getting list's creator email
def created_by_email(id)
  userid = List.find(id)[:user_id]
  listcreatoremail = User.find(userid)[:email]
  return listcreatoremail
end

## verifying if the list has items
def checking_if_tems_in_list(id)
  items = Item.where(list_id: id).count
  if items > 0
    list_empty = false
  else
    list_empty = true
  end
  return list_empty
end

## find all the items that belong to the list
def find_list_items(id)
  items = Item.where(list_id: id)
  return items
end

## getting product name if the product exists
def product_name_for_list(id)
  
    if Product.exists?(id)
      @product_name = Product.find(id)[:article]
    else
      @product_name = "<i class=\"red\">This product had been removed</i>"
      @product_name = @product_name.html_safe
    end
    return @product_name
end

## getting place name if the place exists
def place_name_for_list(id)
  if Place.exists?(id)
    @place_name = Place.find(id)[:title]
  else
    @place_name = "<i class=\"red\">This shop had been removed</i>"
    @place_name = @place_name.html_safe
  end
  return @place_name
end



=begin
def test_umm
  a = 4+4
  return a
end
=end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @item = Item.new
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list }
      else
        format.html { render action: 'new' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:list_id, :list_name, :user_id)
    end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
  <%= form_for(@list) do |f| %>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</p>

      
      <% @list.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :list_name, "List name *"%>
    <%= f.text_field :list_name %>
  </div>
    <%= f.hidden_field :user_id, :value => curr_user_id, :readonly => true %>
  <div class="actions">
    <%= f.submit :class => 'button' %>
    <%= link_to 'Cancel and Back to Lists', lists_path, :class => "button secondary" %>

  </div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

app/views/lists/index.html.erb
<h1>Lists</h1>


<table border = 0 class="lists_table">
  <thead>
    <tr>
      <th>List name</th>
      <th>Creator/Updator</th>
      <th>Items</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  

    <% @lists.each do |list| %>
      <tr>
        <td class="list_name"><%= link_to list.list_name, list, :title => "View List", :class => "list_name"  %></td>
        <td class="creator_email"><%= created_by_email(list.id)  %></td>
        <td class="textaligncenter"><%= Item.where(list_id: list.id).count %></td>
        <td class="action_td"><%= link_to " ", edit_list_path(list), :title => "Edit List", :class => "link_to_edit" %></td>
        <td class="action_td"><%= link_to " ", list, method: :delete, data: { confirm: 'Are you sure?' },:title => "Delete List", :class => "link_to_del" %></td>
      </tr>
    <% end %>
  
</table>


<%= link_to 'New List', new_list_path, class: "button" %>

app/views/lists/new.html.erb
<h1>Add New List</h1>

<%= render 'form' %>

app/views/lists/show.html.erb
<table class="show_items_table">
  <tr>
    <td class="show_items_table_td_left">
      
      <table class="action_table">
        <tr>
          <td class="action_td"><%= link_to " " , edit_list_path(@list), :title => "Edit list", :class => "link_to_edit"%></td>
        </tr>
        <tr>
          <td class="action_td"><%= link_to " ", @list, method: :delete, data: { confirm: 'Are you sure?' }, :title => "Delete List", :class => "link_to_del" %></td>
        </tr>
        <tr>
          <td class="action_td"><%= link_to " ", lists_path, :title => "Go back to Lists", :class => "list_back" %></td>
        </tr>
      </table>
      
      <h1><%= @list.list_name %></h1>
      <p class="creator_email">Created by: &nbsp; <%= created_by_email(params[:id])  %></p>
      
      <div class="clear"></div>
      
      <%
        print checking_if_tems_in_list(params[:id])
        if checking_if_tems_in_list(params[:id]) == true
      %>
           <p class="list_info">The list is empty, add more items using form to the right.</p>
      <%
        else
      %>
        <p class="list_info"><b><%= find_list_items(params[:id]).count %> items</b> in the list</p>
        <table>
          <thead>
          <tr>
            <td class="product_title_td">Product</td>
            <td>Quantity</td>
            <td>Shop</td>
            <td></td>
            <td></td>
          </tr>
          </thead>
          <% find_list_items(params[:id]).order(:place_id).each  do |listitem|%>
          <tr>
            <td><%=h product_name_for_list(listitem[:product_id]) %></td>
            <td><%= listitem[:quantity] %></td>
            <td><%= place_name_for_list(listitem[:place_id]) %></td>
            <td class="action_td"><%= link_to " ", edit_item_path(Item.find(listitem[:id])), :class => "link_to_edit", :title => "Edit Item" %> </td>
            <td class="action_td"><%= link_to " ", listitem, method: :delete, data: { confirm: 'Are you sure?' }, :title => "Delete Item" , :class => "link_to_del"%></td>
          </tr>
          <% end %>
        </table>
        
      <%
        end
      %>
    </td>
    <td class="show_items_table_td_right">
      <h3>Add New Item</h3>

      <div class="small-12">
      <%= form_for @item,  html: {class: "add_item_form"}  do |f| %>
      
        <div class="field">
          <%= f.label :product %>
          <%= f.collection_select :product_id, Product.all.order(:article), :id, :article %>
        </div>
        <div class="field">
          <%= f.label :quantity %>
          <%= f.text_field :quantity %>
        </div>
        <div class="field">
          <%= f.label :place %>
          <%= f.collection_select :place_id, Place.all.order(:title), :id, :title %>
        </div>
          <%= f.hidden_field :list_id, :value => curr_list_id, :readonly => true %>
        <%= f.submit :class => 'button' %>
      <% end %>
      </div>
    </td>
  </tr>
</table>