config/routes.rb
Shoplist::Application.routes.draw do
  
  devise_for :users
  root 'lists#index'
  
  resources :products
  resources :places
  resources :items
  resources :lists
  
  post 'lists/:id' => 'lists#show', as: :go_back_to_list

  

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :list
  has_many :products
  has_many :places
  
  validates_presence_of :product_id, :place_id, :list_id, message: "One of the IDs wasn't sent"
  
end
  
## getting product name
def product_name(id)
  item_product_id = Item.find(id)[:product_id]
  product_name = Product.find(item_product_id)[:article]
  return product_name
end

## getting place name
def place_name(id)
  item_place_id = Item.find(id)[:place_id]
  place_name = Place.find(item_place_id)[:title]
  return place_name
end

## getting list ID
def current_list_id(id)
  #list_id = id
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    @list_id_num = @item[:list_id]
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item.list, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item.list, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to @item.list }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:product_id, :quantity, :place_id, :list_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="small-7">
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@item.errors.count, "error") %> prohibited this place from being saved:</p>

      <% @item.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>

    </div>
  <% end %>


  <div class="form-inputs small-8">
    <%= f.label :product_id %>
    <%= f.collection_select :product_id, Product.all.order(:article), :id, :article %>    


    <%= f.label :quantity %>
    <%= f.text_field :quantity %>


    <%= f.label :place_id %>
    <%= f.collection_select :place_id, Place.all.order(:title), :id, :title %>


    <%= f.label :list_id %>
    <%= f.number_field :list_id %>
  </div>

  <div class="form-actions">
    <%= f.submit :class => 'button' %>
    <%= link_to 'Cancel and Back to List', list_path(@list_id_num), :class => "button secondary"  %>
  </div>
<% end %>
</div>  

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<h1>Registered items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Place</th>
      <th>List_id</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= product_name(item.id) %></td>
        <td><%= item.quantity %></td>
        <td><%= place_name(item.id) %></td>
        <td><%= item.list_id %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to '[X]', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Item', new_item_path, class: "button" %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p>
  <strong>Product ID:</strong>
  <%= product_name(params[:id]) %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Place name:</strong>
  <%= place_name(params[:id]) %>
</p>

<p>
  <strong>List id:</strong>
  <%= @item.list_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>