config/routes.rb
Shoplist::Application.routes.draw do
  
  devise_for :users
  root 'lists#index'
  
  resources :products
  resources :places
  resources :items
  resources :lists
  
  post 'lists/:id' => 'lists#show', as: :go_back_to_list

  

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_many :products
  belongs_to :item
  
  validates :title, uniqueness: true, presence: true

  
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to places_url, notice: 'Place was successfully created.' }
        format.json { render action: 'show', status: :created, location: @place }
      else
        format.html { render action: 'new' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to places_url, notice: 'Place was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:title)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for(@place) do |f| %>
  <% if @place.errors.any? %>
    <div id="error_explanation">
      <p><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</p>

      <% @place.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>

    </div>
  <% end %>

  <div class="field">
    <%= f.label :title, "Shop Title *" %>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'button'%>
    <%= link_to 'Cancel and Back to Shops', places_path, :class => "button secondary" %>

  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Edit Shop</h1>

<%= render 'form' %>

app/views/places/index.html.erb
<h1>Shops</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.title %></td>
        <td class="action_td"><%= link_to " ", edit_place_path(place), :title => "Edit Shop", :class => "link_to_edit"%></td>
        <td class="action_td"><%= link_to " ", place, method: :delete, data: { confirm: 'Are you sure?' }, :title => "Delete Shop", :class => "link_to_del"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add New Shop', new_place_path, class: "button"%>

app/views/places/new.html.erb
<h1>Add New Shop</h1>

<%= render 'form' %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @place.title %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>